service: my-awesome-app

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 10
  stage: production
  region: eu-central-1

functions:
  api:
    handler: lambda.express
    events:
      - http: ANY {proxy+}
      - http: ANY /